apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cluster-services
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.stagingACMEServer | quote }}
    # Email address used for ACME registration
    email: {{ .Values.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable HTTP01 validations
    http01: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cluster-services
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.prodACMEServer | quote }}
    # Email address used for ACME registration
    email: {{ .Values.email | quote }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP01 validations
    http01: {}