# https://github.com/cptactionhank/docker-atlassian-jira-software

image:
  repository: cptactionhank/atlassian-jira-software
  tag: 7.13.0
  pullPolicy: IfNotPresent

jira:
  reverseProxyHost: jira.example.io
  reverseProxyPort: 443
  reverseProxyScheme: https
  javaHeapSize: 1024m
  javaMemoryOptions: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m"
  javaOptions: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - jira.example.io
  tls:
    - secretName: jira.example.io
      hosts:
        - jira.example.io

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  # existingClaim: existing-pvc

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
