apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "atlassian-bitbucket-server.fullname" . }}
  labels:
    app: {{ template "atlassian-bitbucket-server.name" . }}
    chart: {{ template "atlassian-bitbucket-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "atlassian-bitbucket-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "atlassian-bitbucket-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: chown-data-volume
          image: busybox
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["chown", "2:2", "-R", "/data/bitbucket"]
          volumeMounts:
          - name: data
            mountPath: /data/bitbucket
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_SECURE
              value: {{ .Values.bitbucket.serverSecure | quote }}
            - name: SERVER_SCHEME
              value: {{ .Values.bitbucket.serverScheme | quote }}
            - name: SERVER_PROXY_PORT
              value: {{ .Values.bitbucket.serverProxyPort | quote }}
            - name: SERVER_PROXY_NAME
              value: {{ .Values.bitbucket.serverProxyName | quote }}
            - name: JVM_MINIMUM_MEMORY
              value: {{ .Values.bitbucket.jvmMinimumMemory | quote }}
            - name: JVM_MAXIMUM_MEMORY
              value: {{ .Values.bitbucket.jvmMaximumMemory | quote }}
            - name: JVM_SUPPORT_RECOMMENDED_ARGS
              value: {{ .Values.bitbucket.jvmSupportRecommendedArgs | quote }}
          ports:
            - name: http
              containerPort: 7990
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          volumeMounts:
            - name: data
              mountPath: /data/bitbucket
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "atlassian-bitbucket-server.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
