appVersion: 0.22.0
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
engine: gotpl
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
- aws
maintainers:
- email: stefan.henseler@synax.io
  name: Stefan Henseler
name: nginx-ingress-tls
sources:
- https://github.com/kubernetes/ingress-nginx/issues/2724
- https://github.com/kubernetes/ingress-nginx
version: 1.0.3
