apiVersion: v1
appVersion: 1.4.1
name: consul
version: 0.5.4
description: Install and configure Consul on Kubernetes.
home: https://www.consul.io
sources:
  - https://github.com/hashicorp/consul
  - https://github.com/hashicorp/consul-helm
  - https://github.com/hashicorp/consul-k8s